SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [BranchOffice] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertBranchOffice]
	
	@PK_BranchOffice AS INT = -1 ,
	@Code AS NVARCHAR(10) = NULL,
	@Name AS NVARCHAR(50) = NULL,
	@FullAddress AS NVARCHAR(MAX) = NULL,
	@AddressLine1 AS NVARCHAR(250) = NULL,
	@AddressLine2 AS NVARCHAR(250) = NULL,
	@City AS NVARCHAR(100) = NULL,
	@State AS NVARCHAR(100) = NULL,
	@Country AS NVARCHAR(100) = NULL,
	@ZipCode AS NVARCHAR(50) = NULL,
	@Email AS NVARCHAR(300) = NULL,
	@WebSite AS NVARCHAR(200) = NULL,
	@PrimaryPhoneNumber AS NVARCHAR(50) = NULL,
	@SecondaryPhoneNumber AS NVARCHAR(50) = NULL,
	@MobilePhone AS NVARCHAR(50) = NULL,
	@Fax AS NVARCHAR(50) = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_BranchOffice = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [BranchOffice] 
		-- ------------------------------------------------------------
		INSERT INTO [app].[BranchOffice]
		(
		[Code] ,
		[Name] ,
		[FullAddress] ,
		[AddressLine1] ,
		[AddressLine2] ,
		[City] ,
		[State] ,
		[Country] ,
		[ZipCode] ,
		[Email] ,
		[WebSite] ,
		[PrimaryPhoneNumber] ,
		[SecondaryPhoneNumber] ,
		[MobilePhone] ,
		[Fax] )
		OUTPUT Inserted.PK_BranchOffice INTO @Result 
		SELECT 
		@Code,
		@Name,
		@FullAddress,
		@AddressLine1,
		@AddressLine2,
		@City,
		@State,
		@Country,
		@ZipCode,
		@Email,
		@WebSite,
		@PrimaryPhoneNumber,
		@SecondaryPhoneNumber,
		@MobilePhone,
		@Fax
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [BranchOffice] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[Code] = COALESCE(@Code,[ur].[Code]),
		[ur].[Name] = COALESCE(@Name,[ur].[Name]),
		[ur].[FullAddress] = COALESCE(@FullAddress,[ur].[FullAddress]),
		[ur].[AddressLine1] = COALESCE(@AddressLine1,[ur].[AddressLine1]),
		[ur].[AddressLine2] = COALESCE(@AddressLine2,[ur].[AddressLine2]),
		[ur].[City] = COALESCE(@City,[ur].[City]),
		[ur].[State] = COALESCE(@State,[ur].[State]),
		[ur].[Country] = COALESCE(@Country,[ur].[Country]),
		[ur].[ZipCode] = COALESCE(@ZipCode,[ur].[ZipCode]),
		[ur].[Email] = COALESCE(@Email,[ur].[Email]),
		[ur].[WebSite] = COALESCE(@WebSite,[ur].[WebSite]),
		[ur].[PrimaryPhoneNumber] = COALESCE(@PrimaryPhoneNumber,[ur].[PrimaryPhoneNumber]),
		[ur].[SecondaryPhoneNumber] = COALESCE(@SecondaryPhoneNumber,[ur].[SecondaryPhoneNumber]),
		[ur].[MobilePhone] = COALESCE(@MobilePhone,[ur].[MobilePhone]),
		[ur].[Fax] = COALESCE(@Fax,[ur].[Fax])
		FROM [app].[BranchOffice] AS [ur]
		WHERE [PK_BranchOffice] = @PK_BranchOffice
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [app].[BranchOffice] WHERE PK_BranchOffice = @PK_BranchOffice) = 0
	    SET @PK_BranchOffice = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_BranchOffice) AS [PK] 
	-- ------------------------------------------------------------
END
GO
