SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [UserGroup] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertUserGroup]
	
	@PK_UserGroup AS INT = -1 ,
	@FK_User AS INT = NULL,
	@FK_Group AS INT = NULL,
	@Allow AS BIT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_UserGroup = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [UserGroup] 
		-- ------------------------------------------------------------
		INSERT INTO [app].[UserGroup]
		(
		[FK_User] ,
		[FK_Group] ,
		[Allow] )
		OUTPUT Inserted.PK_UserGroup INTO @Result 
		SELECT 
		@FK_User,
		@FK_Group,
		@Allow
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [UserGroup] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[FK_User] = COALESCE(@FK_User,[ur].[FK_User]),
		[ur].[FK_Group] = COALESCE(@FK_Group,[ur].[FK_Group]),
		[ur].[Allow] = COALESCE(@Allow,[ur].[Allow])
		FROM [app].[UserGroup] AS [ur]
		WHERE [PK_UserGroup] = @PK_UserGroup
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [app].[UserGroup] WHERE PK_UserGroup = @PK_UserGroup) = 0
	    SET @PK_UserGroup = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_UserGroup) AS [PK] 
	-- ------------------------------------------------------------
END
GO
