SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [Organization] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertOrganization]
	
	@PK_Organization AS INT = -1 ,
	@Active AS BIT = NULL,
	@ID_Organization AS UNIQUEIDENTIFIER = NULL,
	@FK_Organization__Parent AS INT = NULL,
	@FK_OrganizationType AS INT = NULL,
	@Name AS NVARCHAR(250) = NULL,
	@LegalName AS NVARCHAR(250) = NULL,
	@FullAddress AS NVARCHAR(MAX) = NULL,
	@AddressLine1 AS NVARCHAR(250) = NULL,
	@AddressLine2 AS NVARCHAR(250) = NULL,
	@City AS NVARCHAR(100) = NULL,
	@State AS NVARCHAR(100) = NULL,
	@Country AS NVARCHAR(100) = NULL,
	@ZipCode AS NVARCHAR(50) = NULL,
	@Email AS NVARCHAR(300) = NULL,
	@WebSite AS NVARCHAR(200) = NULL,
	@PrimaryPhoneNumber AS NVARCHAR(50) = NULL,
	@SecondaryPhoneNumber AS NVARCHAR(50) = NULL,
	@MobilePhone AS NVARCHAR(50) = NULL,
	@Fax AS NVARCHAR(50) = NULL,
	@FK_Language AS INT = NULL,
	@Comment AS NVARCHAR(400) = NULL,
	@MarkedAsDeleted AS BIT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_Organization = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [Organization] 
		-- ------------------------------------------------------------
		INSERT INTO [prj].[Organization]
		(
		[Active] ,
		[ID_Organization] ,
		[FK_Organization__Parent] ,
		[FK_OrganizationType] ,
		[Name] ,
		[LegalName] ,
		[FullAddress] ,
		[AddressLine1] ,
		[AddressLine2] ,
		[City] ,
		[State] ,
		[Country] ,
		[ZipCode] ,
		[Email] ,
		[WebSite] ,
		[PrimaryPhoneNumber] ,
		[SecondaryPhoneNumber] ,
		[MobilePhone] ,
		[Fax] ,
		[FK_Language] ,
		[Comment] ,
		[MarkedAsDeleted] )
		OUTPUT Inserted.PK_Organization INTO @Result 
		SELECT 
		@Active,
		@ID_Organization,
		@FK_Organization__Parent,
		@FK_OrganizationType,
		@Name,
		@LegalName,
		@FullAddress,
		@AddressLine1,
		@AddressLine2,
		@City,
		@State,
		@Country,
		@ZipCode,
		@Email,
		@WebSite,
		@PrimaryPhoneNumber,
		@SecondaryPhoneNumber,
		@MobilePhone,
		@Fax,
		@FK_Language,
		@Comment,
		@MarkedAsDeleted
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [Organization] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[Active] = COALESCE(@Active,[ur].[Active]),
		[ur].[ID_Organization] = COALESCE(@ID_Organization,[ur].[ID_Organization]),
		[ur].[FK_Organization__Parent] = COALESCE(@FK_Organization__Parent,[ur].[FK_Organization__Parent]),
		[ur].[FK_OrganizationType] = COALESCE(@FK_OrganizationType,[ur].[FK_OrganizationType]),
		[ur].[Name] = COALESCE(@Name,[ur].[Name]),
		[ur].[LegalName] = COALESCE(@LegalName,[ur].[LegalName]),
		[ur].[FullAddress] = COALESCE(@FullAddress,[ur].[FullAddress]),
		[ur].[AddressLine1] = COALESCE(@AddressLine1,[ur].[AddressLine1]),
		[ur].[AddressLine2] = COALESCE(@AddressLine2,[ur].[AddressLine2]),
		[ur].[City] = COALESCE(@City,[ur].[City]),
		[ur].[State] = COALESCE(@State,[ur].[State]),
		[ur].[Country] = COALESCE(@Country,[ur].[Country]),
		[ur].[ZipCode] = COALESCE(@ZipCode,[ur].[ZipCode]),
		[ur].[Email] = COALESCE(@Email,[ur].[Email]),
		[ur].[WebSite] = COALESCE(@WebSite,[ur].[WebSite]),
		[ur].[PrimaryPhoneNumber] = COALESCE(@PrimaryPhoneNumber,[ur].[PrimaryPhoneNumber]),
		[ur].[SecondaryPhoneNumber] = COALESCE(@SecondaryPhoneNumber,[ur].[SecondaryPhoneNumber]),
		[ur].[MobilePhone] = COALESCE(@MobilePhone,[ur].[MobilePhone]),
		[ur].[Fax] = COALESCE(@Fax,[ur].[Fax]),
		[ur].[FK_Language] = COALESCE(@FK_Language,[ur].[FK_Language]),
		[ur].[Comment] = COALESCE(@Comment,[ur].[Comment]),
		[ur].[MarkedAsDeleted] = COALESCE(@MarkedAsDeleted,[ur].[MarkedAsDeleted])
		FROM [prj].[Organization] AS [ur]
		WHERE [PK_Organization] = @PK_Organization
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [prj].[Organization] WHERE PK_Organization = @PK_Organization) = 0
	    SET @PK_Organization = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_Organization) AS [PK] 
	-- ------------------------------------------------------------
END
GO
