SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [FollowStatus] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertFollowStatus]
	
	@PK_FollowStatus AS INT = -1 ,
	@Name AS NVARCHAR(50) = NULL,
	@Sequence AS INT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_FollowStatus = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [FollowStatus] 
		-- ------------------------------------------------------------
		INSERT INTO [fol].[FollowStatus]
		(
		[Name] ,
		[Sequence] )
		OUTPUT Inserted.PK_FollowStatus INTO @Result 
		SELECT 
		@Name,
		@Sequence
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [FollowStatus] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[Name] = COALESCE(@Name,[ur].[Name]),
		[ur].[Sequence] = COALESCE(@Sequence,[ur].[Sequence])
		FROM [fol].[FollowStatus] AS [ur]
		WHERE [PK_FollowStatus] = @PK_FollowStatus
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [fol].[FollowStatus] WHERE PK_FollowStatus = @PK_FollowStatus) = 0
	    SET @PK_FollowStatus = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_FollowStatus) AS [PK] 
	-- ------------------------------------------------------------
END
GO
