SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [OrganizationContact] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertOrganizationContact]
	
	@PK_OrganizationContact AS INT = -1 ,
	@FK_Organization AS INT = NULL,
	@FK_Contact AS INT = NULL,
	@Comment AS NVARCHAR(4000) = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_OrganizationContact = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [OrganizationContact] 
		-- ------------------------------------------------------------
		INSERT INTO [prj].[OrganizationContact]
		(
		[FK_Organization] ,
		[FK_Contact] ,
		[Comment] )
		OUTPUT Inserted.PK_OrganizationContact INTO @Result 
		SELECT 
		@FK_Organization,
		@FK_Contact,
		@Comment
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [OrganizationContact] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[FK_Organization] = COALESCE(@FK_Organization,[ur].[FK_Organization]),
		[ur].[FK_Contact] = COALESCE(@FK_Contact,[ur].[FK_Contact]),
		[ur].[Comment] = COALESCE(@Comment,[ur].[Comment])
		FROM [prj].[OrganizationContact] AS [ur]
		WHERE [PK_OrganizationContact] = @PK_OrganizationContact
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [prj].[OrganizationContact] WHERE PK_OrganizationContact = @PK_OrganizationContact) = 0
	    SET @PK_OrganizationContact = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_OrganizationContact) AS [PK] 
	-- ------------------------------------------------------------
END
GO
