SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [VersionInfo] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertVersionInfo]
	
	@PK_VersionInfo AS TINYINT = -1 ,
	@Major AS INT = NULL,
	@Minor AS INT = NULL,
	@Revision AS INT = NULL,
	@Build AS INT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_VersionInfo = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [VersionInfo] 
		-- ------------------------------------------------------------
		INSERT INTO [app].[VersionInfo]
		(
		[Major] ,
		[Minor] ,
		[Revision] ,
		[Build] )
		OUTPUT Inserted.PK_VersionInfo INTO @Result 
		SELECT 
		@Major,
		@Minor,
		@Revision,
		@Build
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [VersionInfo] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[Major] = COALESCE(@Major,[ur].[Major]),
		[ur].[Minor] = COALESCE(@Minor,[ur].[Minor]),
		[ur].[Revision] = COALESCE(@Revision,[ur].[Revision]),
		[ur].[Build] = COALESCE(@Build,[ur].[Build])
		FROM [app].[VersionInfo] AS [ur]
		WHERE [PK_VersionInfo] = @PK_VersionInfo
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [app].[VersionInfo] WHERE PK_VersionInfo = @PK_VersionInfo) = 0
	    SET @PK_VersionInfo = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_VersionInfo) AS [PK] 
	-- ------------------------------------------------------------
END
GO
