SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [Building] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertBuilding]
	
	@PK_Building AS INT = -1 ,
	@ID_Building AS UNIQUEIDENTIFIER = NULL,
	@Name AS NVARCHAR(500) = NULL,
	@FullAddress AS NVARCHAR(MAX) = NULL,
	@AddressLine1 AS NVARCHAR(250) = NULL,
	@AddressLine2 AS NVARCHAR(250) = NULL,
	@City AS NVARCHAR(100) = NULL,
	@State AS NVARCHAR(100) = NULL,
	@Country AS NVARCHAR(100) = NULL,
	@ZipCode AS NVARCHAR(50) = NULL,
	@Email AS NVARCHAR(300) = NULL,
	@WebSite AS NVARCHAR(200) = NULL,
	@PrimaryPhoneNumber AS NVARCHAR(50) = NULL,
	@SecondaryPhoneNumber AS NVARCHAR(50) = NULL,
	@MobilePhone AS NVARCHAR(50) = NULL,
	@Fax AS NVARCHAR(50) = NULL,
	@Comment AS NVARCHAR(400) = NULL,
	@MarkedAsDeleted AS BIT = NULL,
	@FK_Organization__Owner AS INT = NULL,
	@FK_Organization__Manager AS INT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_Building = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [Building] 
		-- ------------------------------------------------------------
		INSERT INTO [prj].[Building]
		(
		[ID_Building] ,
		[Name] ,
		[FullAddress] ,
		[AddressLine1] ,
		[AddressLine2] ,
		[City] ,
		[State] ,
		[Country] ,
		[ZipCode] ,
		[Email] ,
		[WebSite] ,
		[PrimaryPhoneNumber] ,
		[SecondaryPhoneNumber] ,
		[MobilePhone] ,
		[Fax] ,
		[Comment] ,
		[MarkedAsDeleted] ,
		[FK_Organization__Owner] ,
		[FK_Organization__Manager] )
		OUTPUT Inserted.PK_Building INTO @Result 
		SELECT 
		@ID_Building,
		@Name,
		@FullAddress,
		@AddressLine1,
		@AddressLine2,
		@City,
		@State,
		@Country,
		@ZipCode,
		@Email,
		@WebSite,
		@PrimaryPhoneNumber,
		@SecondaryPhoneNumber,
		@MobilePhone,
		@Fax,
		@Comment,
		@MarkedAsDeleted,
		@FK_Organization__Owner,
		@FK_Organization__Manager
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [Building] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[ID_Building] = COALESCE(@ID_Building,[ur].[ID_Building]),
		[ur].[Name] = COALESCE(@Name,[ur].[Name]),
		[ur].[FullAddress] = COALESCE(@FullAddress,[ur].[FullAddress]),
		[ur].[AddressLine1] = COALESCE(@AddressLine1,[ur].[AddressLine1]),
		[ur].[AddressLine2] = COALESCE(@AddressLine2,[ur].[AddressLine2]),
		[ur].[City] = COALESCE(@City,[ur].[City]),
		[ur].[State] = COALESCE(@State,[ur].[State]),
		[ur].[Country] = COALESCE(@Country,[ur].[Country]),
		[ur].[ZipCode] = COALESCE(@ZipCode,[ur].[ZipCode]),
		[ur].[Email] = COALESCE(@Email,[ur].[Email]),
		[ur].[WebSite] = COALESCE(@WebSite,[ur].[WebSite]),
		[ur].[PrimaryPhoneNumber] = COALESCE(@PrimaryPhoneNumber,[ur].[PrimaryPhoneNumber]),
		[ur].[SecondaryPhoneNumber] = COALESCE(@SecondaryPhoneNumber,[ur].[SecondaryPhoneNumber]),
		[ur].[MobilePhone] = COALESCE(@MobilePhone,[ur].[MobilePhone]),
		[ur].[Fax] = COALESCE(@Fax,[ur].[Fax]),
		[ur].[Comment] = COALESCE(@Comment,[ur].[Comment]),
		[ur].[MarkedAsDeleted] = COALESCE(@MarkedAsDeleted,[ur].[MarkedAsDeleted]),
		[ur].[FK_Organization__Owner] = COALESCE(@FK_Organization__Owner,[ur].[FK_Organization__Owner]),
		[ur].[FK_Organization__Manager] = COALESCE(@FK_Organization__Manager,[ur].[FK_Organization__Manager])
		FROM [prj].[Building] AS [ur]
		WHERE [PK_Building] = @PK_Building
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [prj].[Building] WHERE PK_Building = @PK_Building) = 0
	    SET @PK_Building = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_Building) AS [PK] 
	-- ------------------------------------------------------------
END
GO
