SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [Employee] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertEmployee]
	
	@PK_Employee AS NVARCHAR(50) = -1 ,
	@Active AS BIT = NULL,
	@EmployeeNumber AS NVARCHAR(50) = NULL,
	@FirstName AS NVARCHAR(50) = NULL,
	@LastName AS NVARCHAR(50) = NULL,
	@FullName AS NVARCHAR(150) = NULL,
	@JobTitle AS NVARCHAR(150) = NULL,
	@BranchOfficeName AS NVARCHAR(150) = NULL,
	@GenericTitle AS NVARCHAR(150) = NULL,
	@OfficePhoneNumber AS NVARCHAR(50) = NULL,
	@MobilePhone AS NVARCHAR(50) = NULL,
	@Extension AS NVARCHAR(50) = NULL,
	@Email AS NVARCHAR(150) = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_Employee = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [Employee] 
		-- ------------------------------------------------------------
		INSERT INTO [app].[Employee]
		(
		[Active] ,
		[EmployeeNumber] ,
		[FirstName] ,
		[LastName] ,
		[FullName] ,
		[JobTitle] ,
		[BranchOfficeName] ,
		[GenericTitle] ,
		[OfficePhoneNumber] ,
		[MobilePhone] ,
		[Extension] ,
		[Email] )
		OUTPUT Inserted.PK_Employee INTO @Result 
		SELECT 
		@Active,
		@EmployeeNumber,
		@FirstName,
		@LastName,
		@FullName,
		@JobTitle,
		@BranchOfficeName,
		@GenericTitle,
		@OfficePhoneNumber,
		@MobilePhone,
		@Extension,
		@Email
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [Employee] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[Active] = COALESCE(@Active,[ur].[Active]),
		[ur].[EmployeeNumber] = COALESCE(@EmployeeNumber,[ur].[EmployeeNumber]),
		[ur].[FirstName] = COALESCE(@FirstName,[ur].[FirstName]),
		[ur].[LastName] = COALESCE(@LastName,[ur].[LastName]),
		[ur].[FullName] = COALESCE(@FullName,[ur].[FullName]),
		[ur].[JobTitle] = COALESCE(@JobTitle,[ur].[JobTitle]),
		[ur].[BranchOfficeName] = COALESCE(@BranchOfficeName,[ur].[BranchOfficeName]),
		[ur].[GenericTitle] = COALESCE(@GenericTitle,[ur].[GenericTitle]),
		[ur].[OfficePhoneNumber] = COALESCE(@OfficePhoneNumber,[ur].[OfficePhoneNumber]),
		[ur].[MobilePhone] = COALESCE(@MobilePhone,[ur].[MobilePhone]),
		[ur].[Extension] = COALESCE(@Extension,[ur].[Extension]),
		[ur].[Email] = COALESCE(@Email,[ur].[Email])
		FROM [app].[Employee] AS [ur]
		WHERE [PK_Employee] = @PK_Employee
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [app].[Employee] WHERE PK_Employee = @PK_Employee) = 0
	    SET @PK_Employee = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_Employee) AS [PK] 
	-- ------------------------------------------------------------
END
GO
