SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [AIOC] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertAIOC]
	
	@PK_AIOC AS INT = -1 ,
	@ObjectIdentifier AS NVARCHAR(50) = NULL,
	@ObjectName AS NVARCHAR(50) = NULL,
	@Description AS NVARCHAR(4000) = NULL,
	@Units AS NVARCHAR(50) = NULL,
	@MaxValue AS REAL = NULL,
	@MinValue AS REAL = NULL,
	@HalFlags AS NVARCHAR(50) = NULL,
	@isAIC AS BIT = NULL,
	@MarkedAsDeleted AS BIT = NULL,
	@HistoricalDateTime AS DATETIME = NULL,
	@ForObjectIdentifier AS NVARCHAR(50) = NULL,
	@FK_ProjectController AS INT = NULL,
	@FK_HistoricalStage AS INT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_AIOC = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [AIOC] 
		-- ------------------------------------------------------------
		INSERT INTO [ctl].[AIOC]
		(
		[ObjectIdentifier] ,
		[ObjectName] ,
		[Description] ,
		[Units] ,
		[MaxValue] ,
		[MinValue] ,
		[HalFlags] ,
		[isAIC] ,
		[MarkedAsDeleted] ,
		[HistoricalDateTime] ,
		[ForObjectIdentifier] ,
		[FK_ProjectController] ,
		[FK_HistoricalStage] )
		OUTPUT Inserted.PK_AIOC INTO @Result 
		SELECT 
		@ObjectIdentifier,
		@ObjectName,
		@Description,
		@Units,
		@MaxValue,
		@MinValue,
		@HalFlags,
		@isAIC,
		@MarkedAsDeleted,
		@HistoricalDateTime,
		@ForObjectIdentifier,
		@FK_ProjectController,
		@FK_HistoricalStage
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [AIOC] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[ObjectIdentifier] = COALESCE(@ObjectIdentifier,[ur].[ObjectIdentifier]),
		[ur].[ObjectName] = COALESCE(@ObjectName,[ur].[ObjectName]),
		[ur].[Description] = COALESCE(@Description,[ur].[Description]),
		[ur].[Units] = COALESCE(@Units,[ur].[Units]),
		[ur].[MaxValue] = COALESCE(@MaxValue,[ur].[MaxValue]),
		[ur].[MinValue] = COALESCE(@MinValue,[ur].[MinValue]),
		[ur].[HalFlags] = COALESCE(@HalFlags,[ur].[HalFlags]),
		[ur].[isAIC] = COALESCE(@isAIC,[ur].[isAIC]),
		[ur].[MarkedAsDeleted] = COALESCE(@MarkedAsDeleted,[ur].[MarkedAsDeleted]),
		[ur].[HistoricalDateTime] = COALESCE(@HistoricalDateTime,[ur].[HistoricalDateTime]),
		[ur].[ForObjectIdentifier] = COALESCE(@ForObjectIdentifier,[ur].[ForObjectIdentifier]),
		[ur].[FK_ProjectController] = COALESCE(@FK_ProjectController,[ur].[FK_ProjectController]),
		[ur].[FK_HistoricalStage] = COALESCE(@FK_HistoricalStage,[ur].[FK_HistoricalStage])
		FROM [ctl].[AIOC] AS [ur]
		WHERE [PK_AIOC] = @PK_AIOC
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [ctl].[AIOC] WHERE PK_AIOC = @PK_AIOC) = 0
	    SET @PK_AIOC = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_AIOC) AS [PK] 
	-- ------------------------------------------------------------
END
GO
