SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [Contact] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertContact]
	
	@PK_Contact AS INT = -1 ,
	@ID_Contact AS UNIQUEIDENTIFIER = NULL,
	@Active AS BIT = NULL,
	@Title AS NVARCHAR(100) = NULL,
	@FirstName AS NVARCHAR(100) = NULL,
	@LastName AS NVARCHAR(100) = NULL,
	@FullName AS NVARCHAR(200) = NULL,
	@FullAddress AS NVARCHAR(MAX) = NULL,
	@AddressLine1 AS NVARCHAR(250) = NULL,
	@AddressLine2 AS NVARCHAR(250) = NULL,
	@City AS NVARCHAR(100) = NULL,
	@State AS NVARCHAR(100) = NULL,
	@Country AS NVARCHAR(100) = NULL,
	@ZipCode AS NVARCHAR(50) = NULL,
	@Email AS NVARCHAR(300) = NULL,
	@WebSite AS NVARCHAR(200) = NULL,
	@PrimaryPhoneNumber AS NVARCHAR(50) = NULL,
	@SecondaryPhoneNumber AS NVARCHAR(50) = NULL,
	@MobilePhone AS NVARCHAR(50) = NULL,
	@Fax AS NVARCHAR(50) = NULL,
	@FK_Language AS INT = NULL,
	@Comment AS NVARCHAR(4000) = NULL,
	@MarkedAsDeleted AS BIT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_Contact = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [Contact] 
		-- ------------------------------------------------------------
		INSERT INTO [prj].[Contact]
		(
		[ID_Contact] ,
		[Active] ,
		[Title] ,
		[FirstName] ,
		[LastName] ,
		[FullName] ,
		[FullAddress] ,
		[AddressLine1] ,
		[AddressLine2] ,
		[City] ,
		[State] ,
		[Country] ,
		[ZipCode] ,
		[Email] ,
		[WebSite] ,
		[PrimaryPhoneNumber] ,
		[SecondaryPhoneNumber] ,
		[MobilePhone] ,
		[Fax] ,
		[FK_Language] ,
		[Comment] ,
		[MarkedAsDeleted] )
		OUTPUT Inserted.PK_Contact INTO @Result 
		SELECT 
		@ID_Contact,
		@Active,
		@Title,
		@FirstName,
		@LastName,
		@FullName,
		@FullAddress,
		@AddressLine1,
		@AddressLine2,
		@City,
		@State,
		@Country,
		@ZipCode,
		@Email,
		@WebSite,
		@PrimaryPhoneNumber,
		@SecondaryPhoneNumber,
		@MobilePhone,
		@Fax,
		@FK_Language,
		@Comment,
		@MarkedAsDeleted
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [Contact] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[ID_Contact] = COALESCE(@ID_Contact,[ur].[ID_Contact]),
		[ur].[Active] = COALESCE(@Active,[ur].[Active]),
		[ur].[Title] = COALESCE(@Title,[ur].[Title]),
		[ur].[FirstName] = COALESCE(@FirstName,[ur].[FirstName]),
		[ur].[LastName] = COALESCE(@LastName,[ur].[LastName]),
		[ur].[FullName] = COALESCE(@FullName,[ur].[FullName]),
		[ur].[FullAddress] = COALESCE(@FullAddress,[ur].[FullAddress]),
		[ur].[AddressLine1] = COALESCE(@AddressLine1,[ur].[AddressLine1]),
		[ur].[AddressLine2] = COALESCE(@AddressLine2,[ur].[AddressLine2]),
		[ur].[City] = COALESCE(@City,[ur].[City]),
		[ur].[State] = COALESCE(@State,[ur].[State]),
		[ur].[Country] = COALESCE(@Country,[ur].[Country]),
		[ur].[ZipCode] = COALESCE(@ZipCode,[ur].[ZipCode]),
		[ur].[Email] = COALESCE(@Email,[ur].[Email]),
		[ur].[WebSite] = COALESCE(@WebSite,[ur].[WebSite]),
		[ur].[PrimaryPhoneNumber] = COALESCE(@PrimaryPhoneNumber,[ur].[PrimaryPhoneNumber]),
		[ur].[SecondaryPhoneNumber] = COALESCE(@SecondaryPhoneNumber,[ur].[SecondaryPhoneNumber]),
		[ur].[MobilePhone] = COALESCE(@MobilePhone,[ur].[MobilePhone]),
		[ur].[Fax] = COALESCE(@Fax,[ur].[Fax]),
		[ur].[FK_Language] = COALESCE(@FK_Language,[ur].[FK_Language]),
		[ur].[Comment] = COALESCE(@Comment,[ur].[Comment]),
		[ur].[MarkedAsDeleted] = COALESCE(@MarkedAsDeleted,[ur].[MarkedAsDeleted])
		FROM [prj].[Contact] AS [ur]
		WHERE [PK_Contact] = @PK_Contact
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [prj].[Contact] WHERE PK_Contact = @PK_Contact) = 0
	    SET @PK_Contact = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_Contact) AS [PK] 
	-- ------------------------------------------------------------
END
GO
