SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [Language] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertLanguage]
	
	@PK_Language AS INT = -1 ,
	@Code AS NVARCHAR(10) = NULL,
	@Name AS NVARCHAR(50) = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_Language = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [Language] 
		-- ------------------------------------------------------------
		INSERT INTO [app].[Language]
		(
		[Code] ,
		[Name] )
		OUTPUT Inserted.PK_Language INTO @Result 
		SELECT 
		@Code,
		@Name
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [Language] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[Code] = COALESCE(@Code,[ur].[Code]),
		[ur].[Name] = COALESCE(@Name,[ur].[Name])
		FROM [app].[Language] AS [ur]
		WHERE [PK_Language] = @PK_Language
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [app].[Language] WHERE PK_Language = @PK_Language) = 0
	    SET @PK_Language = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_Language) AS [PK] 
	-- ------------------------------------------------------------
END
GO
