SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [ProjectOrganization] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertProjectOrganization]
	
	@PK_ProjectOrganization AS INT = -1 ,
	@FK_Project AS INT = NULL,
	@FK_Organization AS INT = NULL,
	@FK_OrganizationType AS INT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_ProjectOrganization = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [ProjectOrganization] 
		-- ------------------------------------------------------------
		INSERT INTO [prj].[ProjectOrganization]
		(
		[FK_Project] ,
		[FK_Organization] ,
		[FK_OrganizationType] )
		OUTPUT Inserted.PK_ProjectOrganization INTO @Result 
		SELECT 
		@FK_Project,
		@FK_Organization,
		@FK_OrganizationType
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [ProjectOrganization] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[FK_Project] = COALESCE(@FK_Project,[ur].[FK_Project]),
		[ur].[FK_Organization] = COALESCE(@FK_Organization,[ur].[FK_Organization]),
		[ur].[FK_OrganizationType] = COALESCE(@FK_OrganizationType,[ur].[FK_OrganizationType])
		FROM [prj].[ProjectOrganization] AS [ur]
		WHERE [PK_ProjectOrganization] = @PK_ProjectOrganization
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [prj].[ProjectOrganization] WHERE PK_ProjectOrganization = @PK_ProjectOrganization) = 0
	    SET @PK_ProjectOrganization = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_ProjectOrganization) AS [PK] 
	-- ------------------------------------------------------------
END
GO
