SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [BuildingBranchOffice] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertBuildingBranchOffice]
	
	@PK_BuildingBranchOffice AS INT = -1 ,
	@FK_Building AS INT = NULL,
	@FK_BranchOffice AS INT = NULL,
	@MarkAsShow AS BIT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_BuildingBranchOffice = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [BuildingBranchOffice] 
		-- ------------------------------------------------------------
		INSERT INTO [prj].[BuildingBranchOffice]
		(
		[FK_Building] ,
		[FK_BranchOffice] ,
		[MarkAsShow] )
		OUTPUT Inserted.PK_BuildingBranchOffice INTO @Result 
		SELECT 
		@FK_Building,
		@FK_BranchOffice,
		@MarkAsShow
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [BuildingBranchOffice] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[FK_Building] = COALESCE(@FK_Building,[ur].[FK_Building]),
		[ur].[FK_BranchOffice] = COALESCE(@FK_BranchOffice,[ur].[FK_BranchOffice]),
		[ur].[MarkAsShow] = COALESCE(@MarkAsShow,[ur].[MarkAsShow])
		FROM [prj].[BuildingBranchOffice] AS [ur]
		WHERE [PK_BuildingBranchOffice] = @PK_BuildingBranchOffice
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [prj].[BuildingBranchOffice] WHERE PK_BuildingBranchOffice = @PK_BuildingBranchOffice) = 0
	    SET @PK_BuildingBranchOffice = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_BuildingBranchOffice) AS [PK] 
	-- ------------------------------------------------------------
END
GO
