SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [BO] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertBO]
	
	@PK_BO AS INT = -1 ,
	@ObjectIdentifier AS NVARCHAR(50) = NULL,
	@ObjectName AS NVARCHAR(50) = NULL,
	@Description AS NVARCHAR(4000) = NULL,
	@PresentValue AS NVARCHAR(50) = NULL,
	@CommissionFlag AS NVARCHAR(50) = NULL,
	@TypeReference AS NVARCHAR(50) = NULL,
	@OutOfService AS INT = NULL,
	@Polarity AS NVARCHAR(50) = NULL,
	@MinimumOffTime AS INT = NULL,
	@MinimumOnTime AS INT = NULL,
	@CriticalControl AS INT = NULL,
	@Reliability AS NVARCHAR(50) = NULL,
	@RelinquishDefault AS NVARCHAR(50) = NULL,
	@HoaStatus AS NVARCHAR(50) = NULL,
	@StartDelayTime AS INT = NULL,
	@FBackEnable AS NVARCHAR(50) = NULL,
	@HalFlags AS NVARCHAR(50) = NULL,
	@EventDetectionEnable AS INT = NULL,
	@MarkedAsDeleted AS BIT = NULL,
	@HistoricalDateTime AS DATETIME = NULL,
	@FK_ProjectController AS INT = NULL,
	@FK_HistoricalStage AS INT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_BO = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [BO] 
		-- ------------------------------------------------------------
		INSERT INTO [ctl].[BO]
		(
		[ObjectIdentifier] ,
		[ObjectName] ,
		[Description] ,
		[PresentValue] ,
		[CommissionFlag] ,
		[TypeReference] ,
		[OutOfService] ,
		[Polarity] ,
		[MinimumOffTime] ,
		[MinimumOnTime] ,
		[CriticalControl] ,
		[Reliability] ,
		[RelinquishDefault] ,
		[HoaStatus] ,
		[StartDelayTime] ,
		[FBackEnable] ,
		[HalFlags] ,
		[EventDetectionEnable] ,
		[MarkedAsDeleted] ,
		[HistoricalDateTime] ,
		[FK_ProjectController] ,
		[FK_HistoricalStage] )
		OUTPUT Inserted.PK_BO INTO @Result 
		SELECT 
		@ObjectIdentifier,
		@ObjectName,
		@Description,
		@PresentValue,
		@CommissionFlag,
		@TypeReference,
		@OutOfService,
		@Polarity,
		@MinimumOffTime,
		@MinimumOnTime,
		@CriticalControl,
		@Reliability,
		@RelinquishDefault,
		@HoaStatus,
		@StartDelayTime,
		@FBackEnable,
		@HalFlags,
		@EventDetectionEnable,
		@MarkedAsDeleted,
		@HistoricalDateTime,
		@FK_ProjectController,
		@FK_HistoricalStage
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [BO] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[ObjectIdentifier] = COALESCE(@ObjectIdentifier,[ur].[ObjectIdentifier]),
		[ur].[ObjectName] = COALESCE(@ObjectName,[ur].[ObjectName]),
		[ur].[Description] = COALESCE(@Description,[ur].[Description]),
		[ur].[PresentValue] = COALESCE(@PresentValue,[ur].[PresentValue]),
		[ur].[CommissionFlag] = COALESCE(@CommissionFlag,[ur].[CommissionFlag]),
		[ur].[TypeReference] = COALESCE(@TypeReference,[ur].[TypeReference]),
		[ur].[OutOfService] = COALESCE(@OutOfService,[ur].[OutOfService]),
		[ur].[Polarity] = COALESCE(@Polarity,[ur].[Polarity]),
		[ur].[MinimumOffTime] = COALESCE(@MinimumOffTime,[ur].[MinimumOffTime]),
		[ur].[MinimumOnTime] = COALESCE(@MinimumOnTime,[ur].[MinimumOnTime]),
		[ur].[CriticalControl] = COALESCE(@CriticalControl,[ur].[CriticalControl]),
		[ur].[Reliability] = COALESCE(@Reliability,[ur].[Reliability]),
		[ur].[RelinquishDefault] = COALESCE(@RelinquishDefault,[ur].[RelinquishDefault]),
		[ur].[HoaStatus] = COALESCE(@HoaStatus,[ur].[HoaStatus]),
		[ur].[StartDelayTime] = COALESCE(@StartDelayTime,[ur].[StartDelayTime]),
		[ur].[FBackEnable] = COALESCE(@FBackEnable,[ur].[FBackEnable]),
		[ur].[HalFlags] = COALESCE(@HalFlags,[ur].[HalFlags]),
		[ur].[EventDetectionEnable] = COALESCE(@EventDetectionEnable,[ur].[EventDetectionEnable]),
		[ur].[MarkedAsDeleted] = COALESCE(@MarkedAsDeleted,[ur].[MarkedAsDeleted]),
		[ur].[HistoricalDateTime] = COALESCE(@HistoricalDateTime,[ur].[HistoricalDateTime]),
		[ur].[FK_ProjectController] = COALESCE(@FK_ProjectController,[ur].[FK_ProjectController]),
		[ur].[FK_HistoricalStage] = COALESCE(@FK_HistoricalStage,[ur].[FK_HistoricalStage])
		FROM [ctl].[BO] AS [ur]
		WHERE [PK_BO] = @PK_BO
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [ctl].[BO] WHERE PK_BO = @PK_BO) = 0
	    SET @PK_BO = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_BO) AS [PK] 
	-- ------------------------------------------------------------
END
GO
