SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [OrganizationType] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertOrganizationType]
	
	@PK_OrganizationType AS INT = -1 ,
	@Name AS NVARCHAR(250) = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_OrganizationType = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [OrganizationType] 
		-- ------------------------------------------------------------
		INSERT INTO [prj].[OrganizationType]
		(
		[Name] )
		OUTPUT Inserted.PK_OrganizationType INTO @Result 
		SELECT 
		@Name
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [OrganizationType] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[Name] = COALESCE(@Name,[ur].[Name])
		FROM [prj].[OrganizationType] AS [ur]
		WHERE [PK_OrganizationType] = @PK_OrganizationType
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [prj].[OrganizationType] WHERE PK_OrganizationType = @PK_OrganizationType) = 0
	    SET @PK_OrganizationType = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_OrganizationType) AS [PK] 
	-- ------------------------------------------------------------
END
GO
