SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [Group] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertGroup]
	
	@PK_Group AS INT = -1 ,
	@Name AS NVARCHAR(100) = NULL,
	@MarkedAsDeleted AS BIT = NULL,
	@FK_Application AS INT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_Group = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [Group] 
		-- ------------------------------------------------------------
		INSERT INTO [app].[Group]
		(
		[Name] ,
		[MarkedAsDeleted] ,
		[FK_Application] )
		OUTPUT Inserted.PK_Group INTO @Result 
		SELECT 
		@Name,
		@MarkedAsDeleted,
		@FK_Application
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [Group] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[Name] = COALESCE(@Name,[ur].[Name]),
		[ur].[MarkedAsDeleted] = COALESCE(@MarkedAsDeleted,[ur].[MarkedAsDeleted]),
		[ur].[FK_Application] = COALESCE(@FK_Application,[ur].[FK_Application])
		FROM [app].[Group] AS [ur]
		WHERE [PK_Group] = @PK_Group
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [app].[Group] WHERE PK_Group = @PK_Group) = 0
	    SET @PK_Group = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_Group) AS [PK] 
	-- ------------------------------------------------------------
END
GO
