SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [HistoricalStage] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertHistoricalStage]
	
	@PK_HistoricalStage AS INT = -1 ,
	@HistoricalStage AS NVARCHAR(50) = NULL,
	@MarkedAsDeleted AS BIT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_HistoricalStage = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [HistoricalStage] 
		-- ------------------------------------------------------------
		INSERT INTO [app].[HistoricalStage]
		(
		[HistoricalStage] ,
		[MarkedAsDeleted] )
		OUTPUT Inserted.PK_HistoricalStage INTO @Result 
		SELECT 
		@HistoricalStage,
		@MarkedAsDeleted
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [HistoricalStage] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[HistoricalStage] = COALESCE(@HistoricalStage,[ur].[HistoricalStage]),
		[ur].[MarkedAsDeleted] = COALESCE(@MarkedAsDeleted,[ur].[MarkedAsDeleted])
		FROM [app].[HistoricalStage] AS [ur]
		WHERE [PK_HistoricalStage] = @PK_HistoricalStage
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [app].[HistoricalStage] WHERE PK_HistoricalStage = @PK_HistoricalStage) = 0
	    SET @PK_HistoricalStage = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_HistoricalStage) AS [PK] 
	-- ------------------------------------------------------------
END
GO
