SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [ProductType] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertProductType]
	
	@PK_ProductType AS INT = -1 ,
	@Code AS NVARCHAR(50) = NULL,
	@Description AS NVARCHAR(200) = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_ProductType = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [ProductType] 
		-- ------------------------------------------------------------
		INSERT INTO [inv].[ProductType]
		(
		[Code] ,
		[Description] )
		OUTPUT Inserted.PK_ProductType INTO @Result 
		SELECT 
		@Code,
		@Description
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [ProductType] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[Code] = COALESCE(@Code,[ur].[Code]),
		[ur].[Description] = COALESCE(@Description,[ur].[Description])
		FROM [inv].[ProductType] AS [ur]
		WHERE [PK_ProductType] = @PK_ProductType
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [inv].[ProductType] WHERE PK_ProductType = @PK_ProductType) = 0
	    SET @PK_ProductType = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_ProductType) AS [PK] 
	-- ------------------------------------------------------------
END
GO
