SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [Project] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertProject]
	
	@PK_Project AS INT = -1 ,
	@FK_BranchOffice AS INT = NULL,
	@FK_Client AS INT = NULL,
	@Active AS BIT = NULL,
	@ProjectNumber AS NVARCHAR(50) = NULL,
	@Description AS NVARCHAR(200) = NULL,
	@OrderDate AS DATETIME = NULL,
	@OpeningDate AS DATETIME = NULL,
	@ClosingDate AS DATETIME = NULL,
	@ProjectManager AS NVARCHAR(100) = NULL,
	@FullAddress AS NVARCHAR(MAX) = NULL,
	@AddressLine1 AS NVARCHAR(250) = NULL,
	@AddressLine2 AS NVARCHAR(250) = NULL,
	@City AS NVARCHAR(100) = NULL,
	@State AS NVARCHAR(100) = NULL,
	@Country AS NVARCHAR(100) = NULL,
	@ZipCode AS NVARCHAR(50) = NULL,
	@Email AS NVARCHAR(300) = NULL,
	@WebSite AS NVARCHAR(200) = NULL,
	@PrimaryPhoneNumber AS NVARCHAR(50) = NULL,
	@SecondaryPhoneNumber AS NVARCHAR(50) = NULL,
	@MobilePhone AS NVARCHAR(50) = NULL,
	@Fax AS NVARCHAR(50) = NULL,
	@Status AS NVARCHAR(1) = NULL,
	@ApplyProjectManagement AS BIT = NULL,
	@Comment AS NVARCHAR(400) = NULL,
	@MarkedAsDeleted AS BIT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_Project = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [Project] 
		-- ------------------------------------------------------------
		INSERT INTO [prj].[Project]
		(
		[FK_BranchOffice] ,
		[FK_Client] ,
		[Active] ,
		[ProjectNumber] ,
		[Description] ,
		[OrderDate] ,
		[OpeningDate] ,
		[ClosingDate] ,
		[ProjectManager] ,
		[FullAddress] ,
		[AddressLine1] ,
		[AddressLine2] ,
		[City] ,
		[State] ,
		[Country] ,
		[ZipCode] ,
		[Email] ,
		[WebSite] ,
		[PrimaryPhoneNumber] ,
		[SecondaryPhoneNumber] ,
		[MobilePhone] ,
		[Fax] ,
		[Status] ,
		[ApplyProjectManagement] ,
		[Comment] ,
		[MarkedAsDeleted] )
		OUTPUT Inserted.PK_Project INTO @Result 
		SELECT 
		@FK_BranchOffice,
		@FK_Client,
		@Active,
		@ProjectNumber,
		@Description,
		@OrderDate,
		@OpeningDate,
		@ClosingDate,
		@ProjectManager,
		@FullAddress,
		@AddressLine1,
		@AddressLine2,
		@City,
		@State,
		@Country,
		@ZipCode,
		@Email,
		@WebSite,
		@PrimaryPhoneNumber,
		@SecondaryPhoneNumber,
		@MobilePhone,
		@Fax,
		@Status,
		@ApplyProjectManagement,
		@Comment,
		@MarkedAsDeleted
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [Project] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[FK_BranchOffice] = COALESCE(@FK_BranchOffice,[ur].[FK_BranchOffice]),
		[ur].[FK_Client] = COALESCE(@FK_Client,[ur].[FK_Client]),
		[ur].[Active] = COALESCE(@Active,[ur].[Active]),
		[ur].[ProjectNumber] = COALESCE(@ProjectNumber,[ur].[ProjectNumber]),
		[ur].[Description] = COALESCE(@Description,[ur].[Description]),
		[ur].[OrderDate] = COALESCE(@OrderDate,[ur].[OrderDate]),
		[ur].[OpeningDate] = COALESCE(@OpeningDate,[ur].[OpeningDate]),
		[ur].[ClosingDate] = COALESCE(@ClosingDate,[ur].[ClosingDate]),
		[ur].[ProjectManager] = COALESCE(@ProjectManager,[ur].[ProjectManager]),
		[ur].[FullAddress] = COALESCE(@FullAddress,[ur].[FullAddress]),
		[ur].[AddressLine1] = COALESCE(@AddressLine1,[ur].[AddressLine1]),
		[ur].[AddressLine2] = COALESCE(@AddressLine2,[ur].[AddressLine2]),
		[ur].[City] = COALESCE(@City,[ur].[City]),
		[ur].[State] = COALESCE(@State,[ur].[State]),
		[ur].[Country] = COALESCE(@Country,[ur].[Country]),
		[ur].[ZipCode] = COALESCE(@ZipCode,[ur].[ZipCode]),
		[ur].[Email] = COALESCE(@Email,[ur].[Email]),
		[ur].[WebSite] = COALESCE(@WebSite,[ur].[WebSite]),
		[ur].[PrimaryPhoneNumber] = COALESCE(@PrimaryPhoneNumber,[ur].[PrimaryPhoneNumber]),
		[ur].[SecondaryPhoneNumber] = COALESCE(@SecondaryPhoneNumber,[ur].[SecondaryPhoneNumber]),
		[ur].[MobilePhone] = COALESCE(@MobilePhone,[ur].[MobilePhone]),
		[ur].[Fax] = COALESCE(@Fax,[ur].[Fax]),
		[ur].[Status] = COALESCE(@Status,[ur].[Status]),
		[ur].[ApplyProjectManagement] = COALESCE(@ApplyProjectManagement,[ur].[ApplyProjectManagement]),
		[ur].[Comment] = COALESCE(@Comment,[ur].[Comment]),
		[ur].[MarkedAsDeleted] = COALESCE(@MarkedAsDeleted,[ur].[MarkedAsDeleted])
		FROM [prj].[Project] AS [ur]
		WHERE [PK_Project] = @PK_Project
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [prj].[Project] WHERE PK_Project = @PK_Project) = 0
	    SET @PK_Project = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_Project) AS [PK] 
	-- ------------------------------------------------------------
END
GO
