SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [Application] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertApplication]
	
	@PK_Application AS INT = -1 ,
	@Name AS NVARCHAR(50) = NULL,
	@MarkedAsDeleted AS BIT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_Application = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [Application] 
		-- ------------------------------------------------------------
		INSERT INTO [app].[Application]
		(
		[Name] ,
		[MarkedAsDeleted] )
		OUTPUT Inserted.PK_Application INTO @Result 
		SELECT 
		@Name,
		@MarkedAsDeleted
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [Application] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[Name] = COALESCE(@Name,[ur].[Name]),
		[ur].[MarkedAsDeleted] = COALESCE(@MarkedAsDeleted,[ur].[MarkedAsDeleted])
		FROM [app].[Application] AS [ur]
		WHERE [PK_Application] = @PK_Application
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [app].[Application] WHERE PK_Application = @PK_Application) = 0
	    SET @PK_Application = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_Application) AS [PK] 
	-- ------------------------------------------------------------
END
GO
