SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [Controller] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertController]
	
	@PK_Controller AS INT = -1 ,
	@ObjectName AS NVARCHAR(50) = NULL,
	@DeviceInstance AS INT = NULL,
	@Description AS NVARCHAR(4000) = NULL,
	@FirmwareRevision AS NVARCHAR(50) = NULL,
	@HardwareRevision AS NVARCHAR(50) = NULL,
	@ApplicationSoftwareVersion AS NVARCHAR(50) = NULL,
	@Location AS NVARCHAR(50) = NULL,
	@Latitude AS REAL = NULL,
	@Longitude AS REAL = NULL,
	@SiteElevation AS INT = NULL,
	@SiteElevationUnits AS NVARCHAR(50) = NULL,
	@HalFlags AS NVARCHAR(50) = NULL,
	@ScanRate AS REAL = NULL,
	@IOScanRate AS REAL = NULL,
	@MarkedAsDeleted AS BIT = NULL,
	@HistoricalDateTime AS DATETIME = NULL,
	@FK_ControllerModel AS INT = NULL,
	@FK_ProjectController AS INT = NULL,
	@FK_HistoricalStage AS INT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_Controller = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [Controller] 
		-- ------------------------------------------------------------
		INSERT INTO [ctl].[Controller]
		(
		[ObjectName] ,
		[DeviceInstance] ,
		[Description] ,
		[FirmwareRevision] ,
		[HardwareRevision] ,
		[ApplicationSoftwareVersion] ,
		[Location] ,
		[Latitude] ,
		[Longitude] ,
		[SiteElevation] ,
		[SiteElevationUnits] ,
		[HalFlags] ,
		[ScanRate] ,
		[IOScanRate] ,
		[MarkedAsDeleted] ,
		[HistoricalDateTime] ,
		[FK_ControllerModel] ,
		[FK_ProjectController] ,
		[FK_HistoricalStage] )
		OUTPUT Inserted.PK_Controller INTO @Result 
		SELECT 
		@ObjectName,
		@DeviceInstance,
		@Description,
		@FirmwareRevision,
		@HardwareRevision,
		@ApplicationSoftwareVersion,
		@Location,
		@Latitude,
		@Longitude,
		@SiteElevation,
		@SiteElevationUnits,
		@HalFlags,
		@ScanRate,
		@IOScanRate,
		@MarkedAsDeleted,
		@HistoricalDateTime,
		@FK_ControllerModel,
		@FK_ProjectController,
		@FK_HistoricalStage
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [Controller] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[ObjectName] = COALESCE(@ObjectName,[ur].[ObjectName]),
		[ur].[DeviceInstance] = COALESCE(@DeviceInstance,[ur].[DeviceInstance]),
		[ur].[Description] = COALESCE(@Description,[ur].[Description]),
		[ur].[FirmwareRevision] = COALESCE(@FirmwareRevision,[ur].[FirmwareRevision]),
		[ur].[HardwareRevision] = COALESCE(@HardwareRevision,[ur].[HardwareRevision]),
		[ur].[ApplicationSoftwareVersion] = COALESCE(@ApplicationSoftwareVersion,[ur].[ApplicationSoftwareVersion]),
		[ur].[Location] = COALESCE(@Location,[ur].[Location]),
		[ur].[Latitude] = COALESCE(@Latitude,[ur].[Latitude]),
		[ur].[Longitude] = COALESCE(@Longitude,[ur].[Longitude]),
		[ur].[SiteElevation] = COALESCE(@SiteElevation,[ur].[SiteElevation]),
		[ur].[SiteElevationUnits] = COALESCE(@SiteElevationUnits,[ur].[SiteElevationUnits]),
		[ur].[HalFlags] = COALESCE(@HalFlags,[ur].[HalFlags]),
		[ur].[ScanRate] = COALESCE(@ScanRate,[ur].[ScanRate]),
		[ur].[IOScanRate] = COALESCE(@IOScanRate,[ur].[IOScanRate]),
		[ur].[MarkedAsDeleted] = COALESCE(@MarkedAsDeleted,[ur].[MarkedAsDeleted]),
		[ur].[HistoricalDateTime] = COALESCE(@HistoricalDateTime,[ur].[HistoricalDateTime]),
		[ur].[FK_ControllerModel] = COALESCE(@FK_ControllerModel,[ur].[FK_ControllerModel]),
		[ur].[FK_ProjectController] = COALESCE(@FK_ProjectController,[ur].[FK_ProjectController]),
		[ur].[FK_HistoricalStage] = COALESCE(@FK_HistoricalStage,[ur].[FK_HistoricalStage])
		FROM [ctl].[Controller] AS [ur]
		WHERE [PK_Controller] = @PK_Controller
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [ctl].[Controller] WHERE PK_Controller = @PK_Controller) = 0
	    SET @PK_Controller = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_Controller) AS [PK] 
	-- ------------------------------------------------------------
END
GO
