SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [AIOCScaleRange] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertAIOCScaleRange]
	
	@PK_AIOCScaleRange AS INT = -1 ,
	@Voltage AS REAL = NULL,
	@Value AS REAL = NULL,
	@AdValue AS INT = NULL,
	@MarkedAsDeleted AS BIT = NULL,
	@HistoricalDateTime AS DATETIME = NULL,
	@AIOCObjectIdentifier AS NVARCHAR(50) = NULL,
	@FK_ProjectController AS INT = NULL,
	@FK_HistoricalStage AS INT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_AIOCScaleRange = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [AIOCScaleRange] 
		-- ------------------------------------------------------------
		INSERT INTO [ctl].[AIOCScaleRange]
		(
		[Voltage] ,
		[Value] ,
		[AdValue] ,
		[MarkedAsDeleted] ,
		[HistoricalDateTime] ,
		[AIOCObjectIdentifier] ,
		[FK_ProjectController] ,
		[FK_HistoricalStage] )
		OUTPUT Inserted.PK_AIOCScaleRange INTO @Result 
		SELECT 
		@Voltage,
		@Value,
		@AdValue,
		@MarkedAsDeleted,
		@HistoricalDateTime,
		@AIOCObjectIdentifier,
		@FK_ProjectController,
		@FK_HistoricalStage
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [AIOCScaleRange] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[Voltage] = COALESCE(@Voltage,[ur].[Voltage]),
		[ur].[Value] = COALESCE(@Value,[ur].[Value]),
		[ur].[AdValue] = COALESCE(@AdValue,[ur].[AdValue]),
		[ur].[MarkedAsDeleted] = COALESCE(@MarkedAsDeleted,[ur].[MarkedAsDeleted]),
		[ur].[HistoricalDateTime] = COALESCE(@HistoricalDateTime,[ur].[HistoricalDateTime]),
		[ur].[AIOCObjectIdentifier] = COALESCE(@AIOCObjectIdentifier,[ur].[AIOCObjectIdentifier]),
		[ur].[FK_ProjectController] = COALESCE(@FK_ProjectController,[ur].[FK_ProjectController]),
		[ur].[FK_HistoricalStage] = COALESCE(@FK_HistoricalStage,[ur].[FK_HistoricalStage])
		FROM [ctl].[AIOCScaleRange] AS [ur]
		WHERE [PK_AIOCScaleRange] = @PK_AIOCScaleRange
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [ctl].[AIOCScaleRange] WHERE PK_AIOCScaleRange = @PK_AIOCScaleRange) = 0
	    SET @PK_AIOCScaleRange = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_AIOCScaleRange) AS [PK] 
	-- ------------------------------------------------------------
END
GO
