SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [ProjectBuilding] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertProjectBuilding]
	
	@PK_ProjectBuilding AS INT = -1 ,
	@FK_Project AS INT = NULL,
	@FK_Building AS INT = NULL,
	@Choosen AS BIT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_ProjectBuilding = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [ProjectBuilding] 
		-- ------------------------------------------------------------
		INSERT INTO [prj].[ProjectBuilding]
		(
		[FK_Project] ,
		[FK_Building] ,
		[Choosen] )
		OUTPUT Inserted.PK_ProjectBuilding INTO @Result 
		SELECT 
		@FK_Project,
		@FK_Building,
		@Choosen
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [ProjectBuilding] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[FK_Project] = COALESCE(@FK_Project,[ur].[FK_Project]),
		[ur].[FK_Building] = COALESCE(@FK_Building,[ur].[FK_Building]),
		[ur].[Choosen] = COALESCE(@Choosen,[ur].[Choosen])
		FROM [prj].[ProjectBuilding] AS [ur]
		WHERE [PK_ProjectBuilding] = @PK_ProjectBuilding
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [prj].[ProjectBuilding] WHERE PK_ProjectBuilding = @PK_ProjectBuilding) = 0
	    SET @PK_ProjectBuilding = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_ProjectBuilding) AS [PK] 
	-- ------------------------------------------------------------
END
GO
