SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [ControllerVersion] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertControllerVersion]
	
	@PK_ControllerVersion AS INT = -1 ,
	@ApplicationVersion AS NVARCHAR(50) = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_ControllerVersion = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [ControllerVersion] 
		-- ------------------------------------------------------------
		INSERT INTO [ctl].[ControllerVersion]
		(
		[ApplicationVersion] )
		OUTPUT Inserted.PK_ControllerVersion INTO @Result 
		SELECT 
		@ApplicationVersion
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [ControllerVersion] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[ApplicationVersion] = COALESCE(@ApplicationVersion,[ur].[ApplicationVersion])
		FROM [ctl].[ControllerVersion] AS [ur]
		WHERE [PK_ControllerVersion] = @PK_ControllerVersion
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [ctl].[ControllerVersion] WHERE PK_ControllerVersion = @PK_ControllerVersion) = 0
	    SET @PK_ControllerVersion = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_ControllerVersion) AS [PK] 
	-- ------------------------------------------------------------
END
GO
