SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [FollowFile] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertFollowFile]
	
	@PK_FollowFile AS INT = -1 ,
	@FilePath AS NVARCHAR(255) = NULL,
	@FK_Follow AS INT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_FollowFile = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [FollowFile] 
		-- ------------------------------------------------------------
		INSERT INTO [fol].[FollowFile]
		(
		[FilePath] ,
		[FK_Follow] )
		OUTPUT Inserted.PK_FollowFile INTO @Result 
		SELECT 
		@FilePath,
		@FK_Follow
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [FollowFile] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[FilePath] = COALESCE(@FilePath,[ur].[FilePath]),
		[ur].[FK_Follow] = COALESCE(@FK_Follow,[ur].[FK_Follow])
		FROM [fol].[FollowFile] AS [ur]
		WHERE [PK_FollowFile] = @PK_FollowFile
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [fol].[FollowFile] WHERE PK_FollowFile = @PK_FollowFile) = 0
	    SET @PK_FollowFile = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_FollowFile) AS [PK] 
	-- ------------------------------------------------------------
END
GO
