SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [Unit] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertUnit]
	
	@PK_Unit AS INT = -1 ,
	@Unit AS NVARCHAR(50) = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_Unit = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [Unit] 
		-- ------------------------------------------------------------
		INSERT INTO [ctl].[Unit]
		(
		[Unit] )
		OUTPUT Inserted.PK_Unit INTO @Result 
		SELECT 
		@Unit
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [Unit] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[Unit] = COALESCE(@Unit,[ur].[Unit])
		FROM [ctl].[Unit] AS [ur]
		WHERE [PK_Unit] = @PK_Unit
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [ctl].[Unit] WHERE PK_Unit = @PK_Unit) = 0
	    SET @PK_Unit = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_Unit) AS [PK] 
	-- ------------------------------------------------------------
END
GO
