SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [ProjectApproval] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertProjectApproval]
	
	@PK_ProjectApproval AS INT = -1 ,
	@FK_Client AS INT = NULL,
	@FK_Building AS INT = NULL,
	@ProjectNumber AS NVARCHAR(50) = NULL,
	@Description AS NVARCHAR(200) = NULL,
	@OrderNumber AS NVARCHAR(100) = NULL,
	@OrderDate AS DATETIME = NULL,
	@SellingPrice AS FLOAT = NULL,
	@NominalPrice AS FLOAT = NULL,
	@ClientCode AS NVARCHAR(50) = NULL,
	@ClientName AS NVARCHAR(250) = NULL,
	@Estimator AS NVARCHAR(250) = NULL,
	@Comment AS NVARCHAR(400) = NULL,
	@Approved AS BIT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_ProjectApproval = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [ProjectApproval] 
		-- ------------------------------------------------------------
		INSERT INTO [prj].[ProjectApproval]
		(
		[FK_Client] ,
		[FK_Building] ,
		[ProjectNumber] ,
		[Description] ,
		[OrderNumber] ,
		[OrderDate] ,
		[SellingPrice] ,
		[NominalPrice] ,
		[ClientCode] ,
		[ClientName] ,
		[Estimator] ,
		[Comment] ,
		[Approved] )
		OUTPUT Inserted.PK_ProjectApproval INTO @Result 
		SELECT 
		@FK_Client,
		@FK_Building,
		@ProjectNumber,
		@Description,
		@OrderNumber,
		@OrderDate,
		@SellingPrice,
		@NominalPrice,
		@ClientCode,
		@ClientName,
		@Estimator,
		@Comment,
		@Approved
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [ProjectApproval] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[FK_Client] = COALESCE(@FK_Client,[ur].[FK_Client]),
		[ur].[FK_Building] = COALESCE(@FK_Building,[ur].[FK_Building]),
		[ur].[ProjectNumber] = COALESCE(@ProjectNumber,[ur].[ProjectNumber]),
		[ur].[Description] = COALESCE(@Description,[ur].[Description]),
		[ur].[OrderNumber] = COALESCE(@OrderNumber,[ur].[OrderNumber]),
		[ur].[OrderDate] = COALESCE(@OrderDate,[ur].[OrderDate]),
		[ur].[SellingPrice] = COALESCE(@SellingPrice,[ur].[SellingPrice]),
		[ur].[NominalPrice] = COALESCE(@NominalPrice,[ur].[NominalPrice]),
		[ur].[ClientCode] = COALESCE(@ClientCode,[ur].[ClientCode]),
		[ur].[ClientName] = COALESCE(@ClientName,[ur].[ClientName]),
		[ur].[Estimator] = COALESCE(@Estimator,[ur].[Estimator]),
		[ur].[Comment] = COALESCE(@Comment,[ur].[Comment]),
		[ur].[Approved] = COALESCE(@Approved,[ur].[Approved])
		FROM [prj].[ProjectApproval] AS [ur]
		WHERE [PK_ProjectApproval] = @PK_ProjectApproval
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [prj].[ProjectApproval] WHERE PK_ProjectApproval = @PK_ProjectApproval) = 0
	    SET @PK_ProjectApproval = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_ProjectApproval) AS [PK] 
	-- ------------------------------------------------------------
END
GO
