SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [ControllerAIOCStd] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertControllerAIOCStd]
	
	@PK_ControllerAIOCStd AS INT = -1 ,
	@FK_ControllerModel AS INT = NULL,
	@FK_AIOCStd AS INT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_ControllerAIOCStd = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [ControllerAIOCStd] 
		-- ------------------------------------------------------------
		INSERT INTO [ctl].[ControllerAIOCStd]
		(
		[FK_ControllerModel] ,
		[FK_AIOCStd] )
		OUTPUT Inserted.PK_ControllerAIOCStd INTO @Result 
		SELECT 
		@FK_ControllerModel,
		@FK_AIOCStd
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [ControllerAIOCStd] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[FK_ControllerModel] = COALESCE(@FK_ControllerModel,[ur].[FK_ControllerModel]),
		[ur].[FK_AIOCStd] = COALESCE(@FK_AIOCStd,[ur].[FK_AIOCStd])
		FROM [ctl].[ControllerAIOCStd] AS [ur]
		WHERE [PK_ControllerAIOCStd] = @PK_ControllerAIOCStd
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [ctl].[ControllerAIOCStd] WHERE PK_ControllerAIOCStd = @PK_ControllerAIOCStd) = 0
	    SET @PK_ControllerAIOCStd = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_ControllerAIOCStd) AS [PK] 
	-- ------------------------------------------------------------
END
GO
