SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [ProjectApprovalOrganization] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertProjectApprovalOrganization]
	
	@PK_ProjectApprovalOrganization AS INT = -1 ,
	@FK_ProjectApproval AS INT = NULL,
	@FK_Organization AS INT = NULL,
	@FK_OrganizationType AS INT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_ProjectApprovalOrganization = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [ProjectApprovalOrganization] 
		-- ------------------------------------------------------------
		INSERT INTO [prj].[ProjectApprovalOrganization]
		(
		[FK_ProjectApproval] ,
		[FK_Organization] ,
		[FK_OrganizationType] )
		OUTPUT Inserted.PK_ProjectApprovalOrganization INTO @Result 
		SELECT 
		@FK_ProjectApproval,
		@FK_Organization,
		@FK_OrganizationType
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [ProjectApprovalOrganization] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[FK_ProjectApproval] = COALESCE(@FK_ProjectApproval,[ur].[FK_ProjectApproval]),
		[ur].[FK_Organization] = COALESCE(@FK_Organization,[ur].[FK_Organization]),
		[ur].[FK_OrganizationType] = COALESCE(@FK_OrganizationType,[ur].[FK_OrganizationType])
		FROM [prj].[ProjectApprovalOrganization] AS [ur]
		WHERE [PK_ProjectApprovalOrganization] = @PK_ProjectApprovalOrganization
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [prj].[ProjectApprovalOrganization] WHERE PK_ProjectApprovalOrganization = @PK_ProjectApprovalOrganization) = 0
	    SET @PK_ProjectApprovalOrganization = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_ProjectApprovalOrganization) AS [PK] 
	-- ------------------------------------------------------------
END
GO
