SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [AIOCScaleRangeStd] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertAIOCScaleRangeStd]
	
	@PK_AIOCScaleRangeStd AS INT = -1 ,
	@Voltage AS REAL = NULL,
	@Value AS REAL = NULL,
	@AdValue AS INT = NULL,
	@MarkedAsDeleted AS BIT = NULL,
	@FK_AIOCStd AS INT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_AIOCScaleRangeStd = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [AIOCScaleRangeStd] 
		-- ------------------------------------------------------------
		INSERT INTO [ctl].[AIOCScaleRangeStd]
		(
		[Voltage] ,
		[Value] ,
		[AdValue] ,
		[MarkedAsDeleted] ,
		[FK_AIOCStd] )
		OUTPUT Inserted.PK_AIOCScaleRangeStd INTO @Result 
		SELECT 
		@Voltage,
		@Value,
		@AdValue,
		@MarkedAsDeleted,
		@FK_AIOCStd
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [AIOCScaleRangeStd] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[Voltage] = COALESCE(@Voltage,[ur].[Voltage]),
		[ur].[Value] = COALESCE(@Value,[ur].[Value]),
		[ur].[AdValue] = COALESCE(@AdValue,[ur].[AdValue]),
		[ur].[MarkedAsDeleted] = COALESCE(@MarkedAsDeleted,[ur].[MarkedAsDeleted]),
		[ur].[FK_AIOCStd] = COALESCE(@FK_AIOCStd,[ur].[FK_AIOCStd])
		FROM [ctl].[AIOCScaleRangeStd] AS [ur]
		WHERE [PK_AIOCScaleRangeStd] = @PK_AIOCScaleRangeStd
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [ctl].[AIOCScaleRangeStd] WHERE PK_AIOCScaleRangeStd = @PK_AIOCScaleRangeStd) = 0
	    SET @PK_AIOCScaleRangeStd = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_AIOCScaleRangeStd) AS [PK] 
	-- ------------------------------------------------------------
END
GO
