SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [FollowInfo] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertFollowInfo]
	
	@PK_FollowInfo AS INT = -1 ,
	@Description AS NVARCHAR(4000) = NULL,
	@TimeStamp AS DATETIME = NULL,
	@HistoricalDateTime AS DATETIME = NULL,
	@FK_Follow AS INT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_FollowInfo = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [FollowInfo] 
		-- ------------------------------------------------------------
		INSERT INTO [fol].[FollowInfo]
		(
		[Description] ,
		[TimeStamp] ,
		[HistoricalDateTime] ,
		[FK_Follow] )
		OUTPUT Inserted.PK_FollowInfo INTO @Result 
		SELECT 
		@Description,
		@TimeStamp,
		@HistoricalDateTime,
		@FK_Follow
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [FollowInfo] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[Description] = COALESCE(@Description,[ur].[Description]),
		[ur].[TimeStamp] = COALESCE(@TimeStamp,[ur].[TimeStamp]),
		[ur].[HistoricalDateTime] = COALESCE(@HistoricalDateTime,[ur].[HistoricalDateTime]),
		[ur].[FK_Follow] = COALESCE(@FK_Follow,[ur].[FK_Follow])
		FROM [fol].[FollowInfo] AS [ur]
		WHERE [PK_FollowInfo] = @PK_FollowInfo
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [fol].[FollowInfo] WHERE PK_FollowInfo = @PK_FollowInfo) = 0
	    SET @PK_FollowInfo = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_FollowInfo) AS [PK] 
	-- ------------------------------------------------------------
END
GO
