SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [GroupPermission] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertGroupPermission]
	
	@PK_GroupPermission AS INT = -1 ,
	@FK_Group AS INT = NULL,
	@FK_Permission AS INT = NULL,
	@Allow AS BIT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_GroupPermission = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [GroupPermission] 
		-- ------------------------------------------------------------
		INSERT INTO [app].[GroupPermission]
		(
		[FK_Group] ,
		[FK_Permission] ,
		[Allow] )
		OUTPUT Inserted.PK_GroupPermission INTO @Result 
		SELECT 
		@FK_Group,
		@FK_Permission,
		@Allow
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [GroupPermission] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[FK_Group] = COALESCE(@FK_Group,[ur].[FK_Group]),
		[ur].[FK_Permission] = COALESCE(@FK_Permission,[ur].[FK_Permission]),
		[ur].[Allow] = COALESCE(@Allow,[ur].[Allow])
		FROM [app].[GroupPermission] AS [ur]
		WHERE [PK_GroupPermission] = @PK_GroupPermission
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [app].[GroupPermission] WHERE PK_GroupPermission = @PK_GroupPermission) = 0
	    SET @PK_GroupPermission = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_GroupPermission) AS [PK] 
	-- ------------------------------------------------------------
END
GO
