SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [AI] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertAI]
	
	@PK_AI AS INT = -1 ,
	@ObjectIdentifier AS NVARCHAR(50) = NULL,
	@ObjectName AS NVARCHAR(50) = NULL,
	@Description AS NVARCHAR(4000) = NULL,
	@PresentValue AS REAL = NULL,
	@CommissionFlag AS NVARCHAR(50) = NULL,
	@TypeReference AS NVARCHAR(50) = NULL,
	@OutOfService AS INT = NULL,
	@CovIncrement AS REAL = NULL,
	@AdFilter AS INT = NULL,
	@Calibration AS REAL = NULL,
	@FixedPoint AS INT = NULL,
	@DecimalPlaces AS INT = NULL,
	@ExternalControl AS INT = NULL,
	@Reliability AS NVARCHAR(50) = NULL,
	@HalFlags AS NVARCHAR(50) = NULL,
	@EventDetectionEnable AS INT = NULL,
	@HistoricalDateTime AS DATETIME = NULL,
	@MarkedAsDeleted AS BIT = NULL,
	@FK_ProjectController AS INT = NULL,
	@FK_HistoricalStage AS INT = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_AI = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [AI] 
		-- ------------------------------------------------------------
		INSERT INTO [ctl].[AI]
		(
		[ObjectIdentifier] ,
		[ObjectName] ,
		[Description] ,
		[PresentValue] ,
		[CommissionFlag] ,
		[TypeReference] ,
		[OutOfService] ,
		[CovIncrement] ,
		[AdFilter] ,
		[Calibration] ,
		[FixedPoint] ,
		[DecimalPlaces] ,
		[ExternalControl] ,
		[Reliability] ,
		[HalFlags] ,
		[EventDetectionEnable] ,
		[HistoricalDateTime] ,
		[MarkedAsDeleted] ,
		[FK_ProjectController] ,
		[FK_HistoricalStage] )
		OUTPUT Inserted.PK_AI INTO @Result 
		SELECT 
		@ObjectIdentifier,
		@ObjectName,
		@Description,
		@PresentValue,
		@CommissionFlag,
		@TypeReference,
		@OutOfService,
		@CovIncrement,
		@AdFilter,
		@Calibration,
		@FixedPoint,
		@DecimalPlaces,
		@ExternalControl,
		@Reliability,
		@HalFlags,
		@EventDetectionEnable,
		@HistoricalDateTime,
		@MarkedAsDeleted,
		@FK_ProjectController,
		@FK_HistoricalStage
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [AI] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[ObjectIdentifier] = COALESCE(@ObjectIdentifier,[ur].[ObjectIdentifier]),
		[ur].[ObjectName] = COALESCE(@ObjectName,[ur].[ObjectName]),
		[ur].[Description] = COALESCE(@Description,[ur].[Description]),
		[ur].[PresentValue] = COALESCE(@PresentValue,[ur].[PresentValue]),
		[ur].[CommissionFlag] = COALESCE(@CommissionFlag,[ur].[CommissionFlag]),
		[ur].[TypeReference] = COALESCE(@TypeReference,[ur].[TypeReference]),
		[ur].[OutOfService] = COALESCE(@OutOfService,[ur].[OutOfService]),
		[ur].[CovIncrement] = COALESCE(@CovIncrement,[ur].[CovIncrement]),
		[ur].[AdFilter] = COALESCE(@AdFilter,[ur].[AdFilter]),
		[ur].[Calibration] = COALESCE(@Calibration,[ur].[Calibration]),
		[ur].[FixedPoint] = COALESCE(@FixedPoint,[ur].[FixedPoint]),
		[ur].[DecimalPlaces] = COALESCE(@DecimalPlaces,[ur].[DecimalPlaces]),
		[ur].[ExternalControl] = COALESCE(@ExternalControl,[ur].[ExternalControl]),
		[ur].[Reliability] = COALESCE(@Reliability,[ur].[Reliability]),
		[ur].[HalFlags] = COALESCE(@HalFlags,[ur].[HalFlags]),
		[ur].[EventDetectionEnable] = COALESCE(@EventDetectionEnable,[ur].[EventDetectionEnable]),
		[ur].[HistoricalDateTime] = COALESCE(@HistoricalDateTime,[ur].[HistoricalDateTime]),
		[ur].[MarkedAsDeleted] = COALESCE(@MarkedAsDeleted,[ur].[MarkedAsDeleted]),
		[ur].[FK_ProjectController] = COALESCE(@FK_ProjectController,[ur].[FK_ProjectController]),
		[ur].[FK_HistoricalStage] = COALESCE(@FK_HistoricalStage,[ur].[FK_HistoricalStage])
		FROM [ctl].[AI] AS [ur]
		WHERE [PK_AI] = @PK_AI
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [ctl].[AI] WHERE PK_AI = @PK_AI) = 0
	    SET @PK_AI = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_AI) AS [PK] 
	-- ------------------------------------------------------------
END
GO
