SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ----------------------------------------------------------------------------
-- INSERT, UPDATE a row for the [Product] table
-- NOTE : DO NOT UPDATE this stored procedure, 
--        the code was autogenerated by usp_GenerateUpsertStodedProcedure
-- ----------------------------------------------------------------------------
--  How to call this stored procedure ....
-- 
-- 	EXEC	@return_value = [dbo].[usp_UpsertCity]
-- 		@PK_City = -1,
-- 		@Code = N'LAV', 
-- 		@Name = N'Laval' 
-- 
-- 
CREATE PROCEDURE [dbo].[usp_UpsertProduct]
	
	@PK_Product AS INT = -1 ,
	@FK_ProductType AS INT = NULL,
	@Code AS NVARCHAR(50) = NULL,
	@Name AS NVARCHAR(150) = NULL,
	@Description AS NVARCHAR(200) = NULL,
	@FK_Organization__Supplier AS INT = NULL,
	@FK_Organization__Manufacturer AS INT = NULL,
	@IsERPProduct AS BIT = NULL,
	@Note AS NVARCHAR(4000) = NULL,
	@ForceOverride BIT = 1
AS
BEGIN

	-- ------------------------------------------------------------
	IF @ForceOverride = 1
	BEGIN
	    SET @ForceOverride=@ForceOverride
	END

	DECLARE @Result  TABLE ( FK int);
	IF @PK_Product = -1
	BEGIN
		-- ------------------------------------------------------------
		-- Insert a row in table  [Product] 
		-- ------------------------------------------------------------
		INSERT INTO [inv].[Product]
		(
		[FK_ProductType] ,
		[Code] ,
		[Name] ,
		[Description] ,
		[FK_Organization__Supplier] ,
		[FK_Organization__Manufacturer] ,
		[IsERPProduct] ,
		[Note] )
		OUTPUT Inserted.PK_Product INTO @Result 
		SELECT 
		@FK_ProductType,
		@Code,
		@Name,
		@Description,
		@FK_Organization__Supplier,
		@FK_Organization__Manufacturer,
		@IsERPProduct,
		@Note
	END ELSE
	BEGIN
		-- ------------------------------------------------------------
		-- Update a row in table  [Product] 
		-- ------------------------------------------------------------
		UPDATE [ur]
		SET 
		[ur].[FK_ProductType] = COALESCE(@FK_ProductType,[ur].[FK_ProductType]),
		[ur].[Code] = COALESCE(@Code,[ur].[Code]),
		[ur].[Name] = COALESCE(@Name,[ur].[Name]),
		[ur].[Description] = COALESCE(@Description,[ur].[Description]),
		[ur].[FK_Organization__Supplier] = COALESCE(@FK_Organization__Supplier,[ur].[FK_Organization__Supplier]),
		[ur].[FK_Organization__Manufacturer] = COALESCE(@FK_Organization__Manufacturer,[ur].[FK_Organization__Manufacturer]),
		[ur].[IsERPProduct] = COALESCE(@IsERPProduct,[ur].[IsERPProduct]),
		[ur].[Note] = COALESCE(@Note,[ur].[Note])
		FROM [inv].[Product] AS [ur]
		WHERE [PK_Product] = @PK_Product
	END;
	-- ------------------------------------------------------------
	IF (SELECT COUNT(*) FROM [inv].[Product] WHERE PK_Product = @PK_Product) = 0
	    SET @PK_Product = -1 ; 
	-- ------------------------------------------------------------
	SELECT COALESCE((SELECT MAX(FK) FROM @Result),@PK_Product) AS [PK] 
	-- ------------------------------------------------------------
END
GO
