SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [app].[Permission](
	[PK_Permission] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) COLLATE French_CI_AS NOT NULL,
	[Value] [nvarchar](100) COLLATE French_CI_AS NOT NULL,
 CONSTRAINT [PK_Webpage] PRIMARY KEY CLUSTERED 
(
	[PK_Permission] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
