SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ctl].[ControllerVersion](
	[PK_ControllerVersion] [int] IDENTITY(1,1) NOT NULL,
	[ApplicationVersion] [nvarchar](50) COLLATE French_CI_AS NOT NULL,
 CONSTRAINT [PK_ControllerVersion] PRIMARY KEY CLUSTERED 
(
	[PK_ControllerVersion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
