SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ctl].[ProjectBuilding](
	[PK_ProjectBuilding] [int] IDENTITY(1,1) NOT NULL,
	[FK_Project] [int] NOT NULL,
	[FK_Building] [int] NOT NULL,
	[Choosen] [bit] NOT NULL,
 CONSTRAINT [PK_ProjectBuilding] PRIMARY KEY CLUSTERED 
(
	[PK_ProjectBuilding] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
