SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ctl].[ObjectMap](
	[PK_ObjectMap] [nvarchar](50) COLLATE French_CI_AS NOT NULL,
	[GroupTag] [nvarchar](50) COLLATE French_CI_AS NOT NULL,
	[ewebTagV3] [nvarchar](50) COLLATE French_CI_AS NOT NULL,
 CONSTRAINT [PK_ObjectMap] PRIMARY KEY CLUSTERED 
(
	[PK_ObjectMap] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
