SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ctl].[AIOCScaleRangeStd](
	[PK_AIOCScaleRangeStd] [int] IDENTITY(1,1) NOT NULL,
	[Voltage] [real] NOT NULL,
	[Value] [real] NOT NULL,
	[AdValue] [int] NOT NULL,
	[MarkedAsDeleted] [bit] NOT NULL,
	[FK_AIOCStd] [int] NOT NULL,
 CONSTRAINT [PK_AicScaleRangeStd] PRIMARY KEY CLUSTERED 
(
	[PK_AIOCScaleRangeStd] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [ctl].[AIOCScaleRangeStd] ADD  CONSTRAINT [DF_AIOCScaleRangeStd_MarkedAsDeleted]  DEFAULT ((0)) FOR [MarkedAsDeleted]
GO
ALTER TABLE [ctl].[AIOCScaleRangeStd]  WITH CHECK ADD  CONSTRAINT [Constraint_FK_AIOCStd_AIOCScaleRangeStd] FOREIGN KEY([FK_AIOCStd])
REFERENCES [ctl].[AIOCStd] ([PK_AIOCStd])
GO
ALTER TABLE [ctl].[AIOCScaleRangeStd] CHECK CONSTRAINT [Constraint_FK_AIOCStd_AIOCScaleRangeStd]
GO
