SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [inv].[ProductType](
	[PK_ProductType] [int] IDENTITY(1,1) NOT NULL,
	[Code] [nvarchar](50) COLLATE French_CI_AS NOT NULL,
	[Description] [nvarchar](200) COLLATE French_CI_AS NOT NULL,
 CONSTRAINT [PK_ProductType] PRIMARY KEY CLUSTERED 
(
	[PK_ProductType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
