SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [prj].[OrganizationType](
	[PK_OrganizationType] [int] NOT NULL,
	[Name] [nvarchar](250) COLLATE French_CI_AS NOT NULL,
 CONSTRAINT [PK_OrganisationType] PRIMARY KEY CLUSTERED 
(
	[PK_OrganizationType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
